### ISSUE TITLE
Move into the (new) contrib repository?

### ISSUE THREAD

**Issue by quicksketch** [mkalkbrenner/xmlrpc#4]
Hi @mkalkbrenner! It's been a long time. :wink:

Would you be interested in moving this code into the rather new [Backdrop Contrib group](https://github.com/backdrop-contrib)?

If so, we'd love to have you added to the group. You can go through the (short) process of getting access to the group here: https://github.com/backdrop-ops/contrib. Thanks for your help on Backdrop in the past. Now that we have an official release, I'd love to see what you think. Thanks!

**Comment by mkalkbrenner** [comment]
Hi Nate,

I’m ok with moving the module to the new contrib repository and created https://github.com/backdrop-ops/contrib/issues/47.

**Comment by quicksketch** [comment]
Great, thanks!
